// GREENLINE 目录册清单（选择界面 hub 的数据源）
// auto-regenerated by apply_catalogs.py
window.CATALOGS = [
  {
    "id": "louver",
    "folder": "louver",
    "category": "machinery",
    "title_cn": "门窗百叶铝框册",
    "title_en": "Aluminium Louver Window & Door Catalogue",
    "desc_cn": "6\"/4\" 铝合金 / 铝塑 / 铁制百叶窗框",
    "desc_en": "6\"/4\" aluminum, aluminum-plastic & iron louver frames",
    "cover_cn": "louver/cover_cn.webp",
    "cover_en": "louver/cover_en.webp",
    "pages": 12
  },
  {
    "id": "rack",
    "folder": "rack",
    "category": "shelves",
    "title_cn": "仓储货架目录册",
    "title_en": "Warehouse Rack Catalogue",
    "desc_cn": "龙昌系列 · 轻型货架 · 仓储设计案例 · 阁楼平台",
    "desc_en": "Long Chang series · light-duty shelving · warehouse cases · mezzanines",
    "cover_cn": "rack/cover_cn.webp",
    "cover_en": "rack/cover_en.webp",
    "pages": 27
  },
  {
    "id": "shelf",
    "folder": "shelf",
    "category": "shelves",
    "title_cn": "商超货架目录册",
    "title_en": "GREENLINE Catalogue",
    "desc_cn": "本润 Benrun · 商超货架 · 仓储货架 · 场景方案",
    "desc_en": "Benrun · supermarket shelves · warehouse racks · store solutions",
    "cover_cn": "shelf/cover_cn.webp",
    "cover_en": "shelf/cover_en.webp",
    "pages": 54
  },
  {
    "id": "bonrun",
    "folder": "bonrun",
    "category": "machinery",
    "title_cn": "本润贸易 GREENLINE INT'L TRADING",
    "title_en": "Bonrun Trade · GREENLINE INT'L TRADING",
    "desc_cn": "本润贸易（广东）—— GREENLINE 进出口业务 · 全球海运、空运、整柜、拼柜、海外仓。广州｜香港｜东南亚｜中东｜非洲｜欧洲｜美洲。",
    "desc_en": "Bonrun Trading (Guangdong) — GREENLINE import & export · ocean, air, FCL, LCL, overseas warehouse. Guangzhou / HK / SEA / ME / Africa / EU / Americas.",
    "cover_cn": "bonrun/cover_cn.webp",
    "cover_en": "bonrun/cover_en.webp",
    "pages": 37
  },
  {
    "id": "brick",
    "folder": "brick",
    "category": "machinery",
    "title_cn": "制砖机产品目录册",
    "title_en": "Brick Machine Catalogue",
    "desc_cn": "KX 系列制砖机 · 自动液压成型机 · 平压机 · 凿岩锤 · 强制式搅拌机。全程一站式砖机供应与技术方案。",
    "desc_en": "KX block machines · automatic hydraulic block making machines · paver presses · jackhammers · mixers. One-stop brick production solutions.",
    "cover_cn": "brick/cover_cn.webp",
    "cover_en": "brick/cover_en.webp",
    "pages": 33
  },
  {
    "id": "boshan",
    "folder": "boshan",
    "category": "machinery",
    "title_cn": "GREENLINE 发电机组产品目录册",
    "title_en": "GREENLINE Power Generator Catalogue",
    "desc_cn": "GREENLINE 发电机组产品目录册，涵盖柴油、燃气、甲醇机组及应用方案。",
    "desc_en": "GREENLINE power generator catalogue covering diesel, gas and methanol gensets.",
    "cover_cn": "boshan/cover_cn.webp",
    "cover_en": "boshan/cover_en.webp",
    "pages": 31
  },
  {
    "id": "autoparts",
    "folder": "autoparts",
    "category": "hardware",
    "title_cn": "GREENLINE 汽车配件目录册",
    "title_en": "GREENLINE Auto Parts Catalogue",
    "desc_cn": "GREENLINE 汽车配件产品目录册。",
    "desc_en": "GREENLINE auto parts catalogue.",
    "cover_cn": "autoparts/cover_cn.webp",
    "cover_en": "autoparts/cover_en.webp",
    "pages": 134
  },
  {
    "id": "packaging_machine",
    "folder": "packaging_machine",
    "category": "machinery",
    "title_cn": "包装机械产品目录册",
    "title_en": "Packaging Machinery Catalogue",
    "desc_cn": "灌装 · 旋盖 · 贴标 · 封口 · 真空包装 · 封箱 · 打码 · 分装 · 枕式包装",
    "desc_en": "Filling · capping · labeling · sealing · vacuum packing · carton sealing · coding · dosing · pillow packaging",
    "cover_cn": "packaging_machine/cover_cn.webp",
    "cover_en": "packaging_machine/cover_en.webp",
    "pages": 74
  },
  {
    "id": "packaging",
    "folder": "packaging",
    "category": "machinery",
    "title_cn": "GREENLINE 食品包装目录册",
    "title_en": "GREENLINE Food Packaging Catalogue",
    "desc_cn": "GREENLINE 食品包装产品目录册。",
    "desc_en": "GREENLINE food packaging catalogue.",
    "cover_cn": "packaging/cover_cn.webp",
    "cover_en": "packaging/cover_en.webp",
    "pages": 24
  },
  {
    "id": "aussieswitch",
    "folder": "aussieswitch",
    "category": "hardware",
    "title_cn": "GREENLINE 澳标开关目录册",
    "title_en": "GREENLINE Australian Standard Switches Catalogue",
    "desc_cn": "GREENLINE 澳标开关插座产品目录册。",
    "desc_en": "GREENLINE Australian standard switches & sockets catalogue.",
    "cover_cn": "aussieswitch/cover_cn.webp",
    "cover_en": "aussieswitch/cover_en.webp",
    "pages": 12
  }
];

// 栏目显示名（hub 标题用）
window.CATALOG_CATS = {
  machinery: { cn: '机械设备', en: 'Machinery' },
  shelves:   { cn: '货架展示', en: 'Shelving & Display' },
  hardware:  { cn: '五金配件', en: 'Hardware' }
};
