// GREENLINE 目录册清单（选择界面 hub 的数据源）
// auto-regenerated by apply_catalogs.py
window.CATALOGS = [
  {
    "id": "louver",
    "folder": "louver",
    "category": "machinery",
    "title_cn": "门窗百叶铝框册",
    "title_en": "Aluminium Louver Window & Door Catalogue",
    "desc_cn": "6\"/4\" 铝合金 / 铝塑 / 铁制百叶窗框",
    "desc_en": "6\"/4\" aluminum, aluminum-plastic & iron louver frames",
    "cover_cn": "louver/cover_cn.webp",
    "cover_en": "louver/cover_en.webp",
    "pages": 12
  },
  {
    "id": "rack",
    "folder": "rack",
    "category": "shelves",
    "title_cn": "仓储货架目录册",
    "title_en": "Warehouse Rack Catalogue",
    "desc_cn": "龙昌系列 · 轻型货架 · 仓储设计案例 · 阁楼平台",
    "desc_en": "Long Chang series · light-duty shelving · warehouse cases · mezzanines",
    "cover_cn": "rack/cover_cn.webp",
    "cover_en": "rack/cover_en.webp",
    "pages": 27
  },
  {
    "id": "shelf",
    "folder": "shelf",
    "category": "shelves",
    "title_cn": "商超货架目录册",
    "title_en": "GREENLINE Catalogue",
    "desc_cn": "本润 Benrun · 商超货架 · 仓储货架 · 场景方案",
    "desc_en": "Benrun · supermarket shelves · warehouse racks · store solutions",
    "cover_cn": "shelf/cover_cn.webp",
    "cover_en": "shelf/cover_en.webp",
    "pages": 54
  },
  {
    "id": "lianteng",
    "folder": "lianteng",
    "category": "machinery",
    "title_cn": "包装机械目录册",
    "title_en": "Packaging Machinery Catalogue",
    "desc_cn": "灌装 · 旋盖 · 贴标 · 封口 · 真空包装 · 封箱 · 打码 · 分装 · 枕式包装",
    "desc_en": "Filling · capping · labeling · sealing · vacuum packing · carton sealing · coding · dosing · pillow packaging",
    "cover_cn": "lianteng/cover_cn.webp",
    "cover_en": "lianteng/cover_en.webp",
    "pages": 37
  },
  {
    "id": "machinery",
    "folder": "machinery",
    "category": "machinery",
    "title_cn": "制砖机产品目录册",
    "title_en": "Brick Machine Catalogue",
    "desc_cn": "GREENLINE 制砖机械产品目录册，展示砖机设备与技术方案。",
    "desc_en": "GREENLINE brick making machinery catalogue.",
    "cover_cn": "machinery/cover_cn.webp",
    "cover_en": "machinery/cover_en.webp",
    "pages": 33
  },
  {
    "id": "boshan",
    "folder": "boshan",
    "category": "machinery",
    "title_cn": "GREENLINE 发电机组产品目录册",
    "title_en": "GREENLINE Power Generator Catalogue",
    "desc_cn": "GREENLINE 发电机组产品目录册，涵盖柴油、燃气、甲醇机组及应用方案。",
    "desc_en": "GREENLINE power generator catalogue covering diesel, gas and methanol gensets.",
    "cover_cn": "boshan/cover_cn.webp",
    "cover_en": "boshan/cover_en.webp",
    "pages": 31
  },
  {
    "id": "autoparts",
    "folder": "autoparts",
    "category": "hardware",
    "title_cn": "GREENLINE 汽车配件目录册",
    "title_en": "GREENLINE Auto Parts Catalogue",
    "desc_cn": "GREENLINE 汽车配件产品目录册。",
    "desc_en": "GREENLINE auto parts catalogue.",
    "cover_cn": "autoparts/cover_cn.webp",
    "cover_en": "autoparts/cover_en.webp",
    "pages": 134
  },
  {
    "id": "packaging",
    "folder": "packaging",
    "category": "machinery",
    "title_cn": "GREENLINE 食品包装目录册",
    "title_en": "GREENLINE Food Packaging Catalogue",
    "desc_cn": "GREENLINE 食品包装产品目录册。",
    "desc_en": "GREENLINE food packaging catalogue.",
    "cover_cn": "packaging/cover_cn.webp",
    "cover_en": "packaging/cover_en.webp",
    "pages": 24
  },
  {
    "id": "aussieswitch",
    "folder": "aussieswitch",
    "category": "hardware",
    "title_cn": "GREENLINE 澳标开关目录册",
    "title_en": "GREENLINE Australian Standard Switches Catalogue",
    "desc_cn": "GREENLINE 澳标开关插座产品目录册。",
    "desc_en": "GREENLINE Australian standard switches & sockets catalogue.",
    "cover_cn": "aussieswitch/cover_cn.webp",
    "cover_en": "aussieswitch/cover_en.webp",
    "pages": 12
  },
  {
    "id": "cast_aluminum",
    "folder": "cast_aluminum",
    "category": "doors",
    "title_cn": "铸铝精雕门板图册",
    "title_en": "Cast Aluminum Carved Door Panel Catalogue",
    "desc_cn": "高端铸铝精雕门板 · 别墅入户门花板系列 · 264 款雕刻工艺。",
    "desc_en": "High-end cast aluminum carved door panels · villa entrance door carving series · 264 designs.",
    "cover_cn": "covers/cast_aluminum.webp",
    "cover_en": "covers/cast_aluminum_en.webp",
    "pages": 264
  },
  {
    "id": "junli",
    "folder": "junli",
    "category": "doors",
    "title_cn": "铜艺大门图册",
    "title_en": "Bronze Entrance Door Catalogue",
    "desc_cn": "铜艺铸铝大门 · 罗马柱款式 · 精雕花板系列。",
    "desc_en": "Bronze & cast aluminum entrance doors · Roman column styles · carved panel series.",
    "cover_cn": "covers/junli.webp",
    "cover_en": "covers/junli_en.webp",
    "pages": 97
  },
  {
    "id": "furuisi",
    "folder": "furuisi",
    "category": "doors",
    "title_cn": "断桥铝系统窗图册",
    "title_en": "Thermal-Break Aluminum Windows Catalogue",
    "desc_cn": "88/98 系列断桥铝平开纱窗一体 · 50 系列非断桥平开窗。",
    "desc_en": "88/98 series thermal-break tilt-turn casement windows with screen · 50 series non-thermal break windows.",
    "cover_cn": "covers/furuisi.webp",
    "cover_en": "covers/furuisi_en.webp",
    "pages": 24
  },
  {
    "id": "dianzi_copy",
    "folder": "dianzi_copy",
    "category": "doors",
    "title_cn": "防盗安全门图册",
    "title_en": "Security Door Catalogue",
    "desc_cn": "防盗安全门 · 精雕面板门 · 智能锁系列。",
    "desc_en": "Security entrance doors · carved panel doors · smart lock series.",
    "cover_cn": "covers/dianzi_copy.webp",
    "cover_en": "covers/dianzi_copy_en.webp",
    "pages": 97
  }
];

// 栏目显示名（hub 标题用）
window.CATALOG_CATS = {
  machinery: { cn: '机械设备', en: 'Machinery' },
  shelves:   { cn: '货架展示', en: 'Shelving & Display' },
  hardware:  { cn: '五金配件', en: 'Hardware' },
  doors:     { cn: '门窗', en: 'Doors & Windows' }
};
