// GREENLINE Packaging Machinery Catalogue · generated by _gen_pm_pages.py
window.FLIP = {
  "total": 74,
  "title_cn": "GREENLINE 包装机械产品目录册",
  "title_en": "GREENLINE Packaging Machinery Catalogue",
  "subtitle_cn": "灌装 · 旋盖 · 贴标 · 封口 · 真空包装 · 封箱 · 打码 · 分装 · 枕式包装",
  "subtitle_en": "Filling · Capping · Labeling · Sealing · Vacuum · Carton · Coding · Dosing · Pillow",
  "items": [
    {
      "i": 1,
      "name": "封面 Cover",
      "descr": "GREENLINE Packaging Machinery Catalogue"
    },
    {
      "i": 2,
      "name": "灌装机 (Filling Machine) p.02",
      "descr": "GL-0802  ·  Filling Machine Technical & Application"
    },
    {
      "i": 3,
      "name": "灌装机 (Filling Machine) p.03",
      "descr": "GL-0803  ·  Filling Machine Technical & Application"
    },
    {
      "i": 4,
      "name": "灌装机 (Filling Machine) p.04",
      "descr": "GL-0804  ·  Filling Machine Technical & Application"
    },
    {
      "i": 5,
      "name": "灌装机 (Filling Machine) p.05",
      "descr": "GL-0805  ·  Filling Machine Technical & Application"
    },
    {
      "i": 6,
      "name": "灌装机 (Filling Machine) p.06",
      "descr": "GL-0806  ·  Filling Machine Technical & Application"
    },
    {
      "i": 7,
      "name": "灌装机 (Filling Machine) p.07",
      "descr": "GL-0807  ·  Filling Machine Technical & Application"
    },
    {
      "i": 8,
      "name": "灌装机 (Filling Machine) p.08",
      "descr": "GL-0808  ·  Filling Machine Technical & Application"
    },
    {
      "i": 9,
      "name": "旋盖机 (Capping Machine) p.09",
      "descr": "GL-0809  ·  Capping Machine Technical & Application"
    },
    {
      "i": 10,
      "name": "旋盖机 (Capping Machine) p.10",
      "descr": "GL-0810  ·  Capping Machine Technical & Application"
    },
    {
      "i": 11,
      "name": "旋盖机 (Capping Machine) p.11",
      "descr": "GL-0811  ·  Capping Machine Technical & Application"
    },
    {
      "i": 12,
      "name": "旋盖机 (Capping Machine) p.12",
      "descr": "GL-0812  ·  Capping Machine Technical & Application"
    },
    {
      "i": 13,
      "name": "旋盖机 (Capping Machine) p.13",
      "descr": "GL-0813  ·  Capping Machine Technical & Application"
    },
    {
      "i": 14,
      "name": "旋盖机 (Capping Machine) p.14",
      "descr": "GL-0814  ·  Capping Machine Technical & Application"
    },
    {
      "i": 15,
      "name": "旋盖机 (Capping Machine) p.15",
      "descr": "GL-0815  ·  Capping Machine Technical & Application"
    },
    {
      "i": 16,
      "name": "旋盖机 (Capping Machine) p.16",
      "descr": "GL-0816  ·  Capping Machine Technical & Application"
    },
    {
      "i": 17,
      "name": "贴标机 (Labeling Machine) p.17",
      "descr": "GL-0817  ·  Labeling Machine Technical & Application"
    },
    {
      "i": 18,
      "name": "贴标机 (Labeling Machine) p.18",
      "descr": "GL-0818  ·  Labeling Machine Technical & Application"
    },
    {
      "i": 19,
      "name": "贴标机 (Labeling Machine) p.19",
      "descr": "GL-0819  ·  Labeling Machine Technical & Application"
    },
    {
      "i": 20,
      "name": "贴标机 (Labeling Machine) p.20",
      "descr": "GL-0820  ·  Labeling Machine Technical & Application"
    },
    {
      "i": 21,
      "name": "贴标机 (Labeling Machine) p.21",
      "descr": "GL-0821  ·  Labeling Machine Technical & Application"
    },
    {
      "i": 22,
      "name": "贴标机 (Labeling Machine) p.22",
      "descr": "GL-0822  ·  Labeling Machine Technical & Application"
    },
    {
      "i": 23,
      "name": "贴标机 (Labeling Machine) p.23",
      "descr": "GL-0823  ·  Labeling Machine Technical & Application"
    },
    {
      "i": 24,
      "name": "贴标机 (Labeling Machine) p.24",
      "descr": "GL-0824  ·  Labeling Machine Technical & Application"
    },
    {
      "i": 25,
      "name": "封口机 (Sealing Machine) p.25",
      "descr": "GL-0825  ·  Sealing Machine Technical & Application"
    },
    {
      "i": 26,
      "name": "封口机 (Sealing Machine) p.26",
      "descr": "GL-0826  ·  Sealing Machine Technical & Application"
    },
    {
      "i": 27,
      "name": "封口机 (Sealing Machine) p.27",
      "descr": "GL-0827  ·  Sealing Machine Technical & Application"
    },
    {
      "i": 28,
      "name": "封口机 (Sealing Machine) p.28",
      "descr": "GL-0828  ·  Sealing Machine Technical & Application"
    },
    {
      "i": 29,
      "name": "封口机 (Sealing Machine) p.29",
      "descr": "GL-0829  ·  Sealing Machine Technical & Application"
    },
    {
      "i": 30,
      "name": "封口机 (Sealing Machine) p.30",
      "descr": "GL-0830  ·  Sealing Machine Technical & Application"
    },
    {
      "i": 31,
      "name": "封口机 (Sealing Machine) p.31",
      "descr": "GL-0831  ·  Sealing Machine Technical & Application"
    },
    {
      "i": 32,
      "name": "封口机 (Sealing Machine) p.32",
      "descr": "GL-0832  ·  Sealing Machine Technical & Application"
    },
    {
      "i": 33,
      "name": "真空包装机 (Vacuum Packing) p.33",
      "descr": "GL-0833  ·  Vacuum Packing Technical & Application"
    },
    {
      "i": 34,
      "name": "真空包装机 (Vacuum Packing) p.34",
      "descr": "GL-0834  ·  Vacuum Packing Technical & Application"
    },
    {
      "i": 35,
      "name": "真空包装机 (Vacuum Packing) p.35",
      "descr": "GL-0835  ·  Vacuum Packing Technical & Application"
    },
    {
      "i": 36,
      "name": "真空包装机 (Vacuum Packing) p.36",
      "descr": "GL-0836  ·  Vacuum Packing Technical & Application"
    },
    {
      "i": 37,
      "name": "真空包装机 (Vacuum Packing) p.37",
      "descr": "GL-0837  ·  Vacuum Packing Technical & Application"
    },
    {
      "i": 38,
      "name": "真空包装机 (Vacuum Packing) p.38",
      "descr": "GL-0838  ·  Vacuum Packing Technical & Application"
    },
    {
      "i": 39,
      "name": "真空包装机 (Vacuum Packing) p.39",
      "descr": "GL-0839  ·  Vacuum Packing Technical & Application"
    },
    {
      "i": 40,
      "name": "真空包装机 (Vacuum Packing) p.40",
      "descr": "GL-0840  ·  Vacuum Packing Technical & Application"
    },
    {
      "i": 41,
      "name": "封箱机 (Carton Sealing) p.41",
      "descr": "GL-0841  ·  Carton Sealing Technical & Application"
    },
    {
      "i": 42,
      "name": "封箱机 (Carton Sealing) p.42",
      "descr": "GL-0842  ·  Carton Sealing Technical & Application"
    },
    {
      "i": 43,
      "name": "封箱机 (Carton Sealing) p.43",
      "descr": "GL-0843  ·  Carton Sealing Technical & Application"
    },
    {
      "i": 44,
      "name": "封箱机 (Carton Sealing) p.44",
      "descr": "GL-0844  ·  Carton Sealing Technical & Application"
    },
    {
      "i": 45,
      "name": "封箱机 (Carton Sealing) p.45",
      "descr": "GL-0845  ·  Carton Sealing Technical & Application"
    },
    {
      "i": 46,
      "name": "封箱机 (Carton Sealing) p.46",
      "descr": "GL-0846  ·  Carton Sealing Technical & Application"
    },
    {
      "i": 47,
      "name": "封箱机 (Carton Sealing) p.47",
      "descr": "GL-0847  ·  Carton Sealing Technical & Application"
    },
    {
      "i": 48,
      "name": "封箱机 (Carton Sealing) p.48",
      "descr": "GL-0848  ·  Carton Sealing Technical & Application"
    },
    {
      "i": 49,
      "name": "打码机 (Coding Marking) p.49",
      "descr": "GL-0849  ·  Coding Marking Technical & Application"
    },
    {
      "i": 50,
      "name": "打码机 (Coding Marking) p.50",
      "descr": "GL-0850  ·  Coding Marking Technical & Application"
    },
    {
      "i": 51,
      "name": "打码机 (Coding Marking) p.51",
      "descr": "GL-0851  ·  Coding Marking Technical & Application"
    },
    {
      "i": 52,
      "name": "打码机 (Coding Marking) p.52",
      "descr": "GL-0852  ·  Coding Marking Technical & Application"
    },
    {
      "i": 53,
      "name": "打码机 (Coding Marking) p.53",
      "descr": "GL-0853  ·  Coding Marking Technical & Application"
    },
    {
      "i": 54,
      "name": "打码机 (Coding Marking) p.54",
      "descr": "GL-0854  ·  Coding Marking Technical & Application"
    },
    {
      "i": 55,
      "name": "打码机 (Coding Marking) p.55",
      "descr": "GL-0855  ·  Coding Marking Technical & Application"
    },
    {
      "i": 56,
      "name": "打码机 (Coding Marking) p.56",
      "descr": "GL-0856  ·  Coding Marking Technical & Application"
    },
    {
      "i": 57,
      "name": "分装机 (Dosing Machine) p.57",
      "descr": "GL-0857  ·  Dosing Machine Technical & Application"
    },
    {
      "i": 58,
      "name": "分装机 (Dosing Machine) p.58",
      "descr": "GL-0858  ·  Dosing Machine Technical & Application"
    },
    {
      "i": 59,
      "name": "分装机 (Dosing Machine) p.59",
      "descr": "GL-0859  ·  Dosing Machine Technical & Application"
    },
    {
      "i": 60,
      "name": "分装机 (Dosing Machine) p.60",
      "descr": "GL-0860  ·  Dosing Machine Technical & Application"
    },
    {
      "i": 61,
      "name": "分装机 (Dosing Machine) p.61",
      "descr": "GL-0861  ·  Dosing Machine Technical & Application"
    },
    {
      "i": 62,
      "name": "分装机 (Dosing Machine) p.62",
      "descr": "GL-0862  ·  Dosing Machine Technical & Application"
    },
    {
      "i": 63,
      "name": "分装机 (Dosing Machine) p.63",
      "descr": "GL-0863  ·  Dosing Machine Technical & Application"
    },
    {
      "i": 64,
      "name": "分装机 (Dosing Machine) p.64",
      "descr": "GL-0864  ·  Dosing Machine Technical & Application"
    },
    {
      "i": 65,
      "name": "枕式包装机 (Pillow Packing) p.65",
      "descr": "GL-0865  ·  Pillow Packing Technical & Application"
    },
    {
      "i": 66,
      "name": "枕式包装机 (Pillow Packing) p.66",
      "descr": "GL-0866  ·  Pillow Packing Technical & Application"
    },
    {
      "i": 67,
      "name": "枕式包装机 (Pillow Packing) p.67",
      "descr": "GL-0867  ·  Pillow Packing Technical & Application"
    },
    {
      "i": 68,
      "name": "枕式包装机 (Pillow Packing) p.68",
      "descr": "GL-0868  ·  Pillow Packing Technical & Application"
    },
    {
      "i": 69,
      "name": "枕式包装机 (Pillow Packing) p.69",
      "descr": "GL-0869  ·  Pillow Packing Technical & Application"
    },
    {
      "i": 70,
      "name": "枕式包装机 (Pillow Packing) p.70",
      "descr": "GL-0870  ·  Pillow Packing Technical & Application"
    },
    {
      "i": 71,
      "name": "枕式包装机 (Pillow Packing) p.71",
      "descr": "GL-0871  ·  Pillow Packing Technical & Application"
    },
    {
      "i": 72,
      "name": "枕式包装机 (Pillow Packing) p.72",
      "descr": "GL-0872  ·  Pillow Packing Technical & Application"
    },
    {
      "i": 73,
      "name": "枕式包装机 (Pillow Packing) p.73",
      "descr": "GL-0873  ·  Pillow Packing Technical & Application"
    },
    {
      "i": 74,
      "name": "封底 Back Cover",
      "descr": "Bonrun Trading — Contact Information"
    }
  ],
  "images": [
    "pages/full/p001.jpg",
    "pages/full/p002.jpg",
    "pages/full/p003.jpg",
    "pages/full/p004.jpg",
    "pages/full/p005.jpg",
    "pages/full/p006.jpg",
    "pages/full/p007.jpg",
    "pages/full/p008.jpg",
    "pages/full/p009.jpg",
    "pages/full/p010.jpg",
    "pages/full/p011.jpg",
    "pages/full/p012.jpg",
    "pages/full/p013.jpg",
    "pages/full/p014.jpg",
    "pages/full/p015.jpg",
    "pages/full/p016.jpg",
    "pages/full/p017.jpg",
    "pages/full/p018.jpg",
    "pages/full/p019.jpg",
    "pages/full/p020.jpg",
    "pages/full/p021.jpg",
    "pages/full/p022.jpg",
    "pages/full/p023.jpg",
    "pages/full/p024.jpg",
    "pages/full/p025.jpg",
    "pages/full/p026.jpg",
    "pages/full/p027.jpg",
    "pages/full/p028.jpg",
    "pages/full/p029.jpg",
    "pages/full/p030.jpg",
    "pages/full/p031.jpg",
    "pages/full/p032.jpg",
    "pages/full/p033.jpg",
    "pages/full/p034.jpg",
    "pages/full/p035.jpg",
    "pages/full/p036.jpg",
    "pages/full/p037.jpg",
    "pages/full/p038.jpg",
    "pages/full/p039.jpg",
    "pages/full/p040.jpg",
    "pages/full/p041.jpg",
    "pages/full/p042.jpg",
    "pages/full/p043.jpg",
    "pages/full/p044.jpg",
    "pages/full/p045.jpg",
    "pages/full/p046.jpg",
    "pages/full/p047.jpg",
    "pages/full/p048.jpg",
    "pages/full/p049.jpg",
    "pages/full/p050.jpg",
    "pages/full/p051.jpg",
    "pages/full/p052.jpg",
    "pages/full/p053.jpg",
    "pages/full/p054.jpg",
    "pages/full/p055.jpg",
    "pages/full/p056.jpg",
    "pages/full/p057.jpg",
    "pages/full/p058.jpg",
    "pages/full/p059.jpg",
    "pages/full/p060.jpg",
    "pages/full/p061.jpg",
    "pages/full/p062.jpg",
    "pages/full/p063.jpg",
    "pages/full/p064.jpg",
    "pages/full/p065.jpg",
    "pages/full/p066.jpg",
    "pages/full/p067.jpg",
    "pages/full/p068.jpg",
    "pages/full/p069.jpg",
    "pages/full/p070.jpg",
    "pages/full/p071.jpg",
    "pages/full/p072.jpg",
    "pages/full/p073.jpg",
    "pages/full/p074.jpg"
  ],
  "thumbs": [
    "pages/thumbs/p001.jpg",
    "pages/thumbs/p002.jpg",
    "pages/thumbs/p003.jpg",
    "pages/thumbs/p004.jpg",
    "pages/thumbs/p005.jpg",
    "pages/thumbs/p006.jpg",
    "pages/thumbs/p007.jpg",
    "pages/thumbs/p008.jpg",
    "pages/thumbs/p009.jpg",
    "pages/thumbs/p010.jpg",
    "pages/thumbs/p011.jpg",
    "pages/thumbs/p012.jpg",
    "pages/thumbs/p013.jpg",
    "pages/thumbs/p014.jpg",
    "pages/thumbs/p015.jpg",
    "pages/thumbs/p016.jpg",
    "pages/thumbs/p017.jpg",
    "pages/thumbs/p018.jpg",
    "pages/thumbs/p019.jpg",
    "pages/thumbs/p020.jpg",
    "pages/thumbs/p021.jpg",
    "pages/thumbs/p022.jpg",
    "pages/thumbs/p023.jpg",
    "pages/thumbs/p024.jpg",
    "pages/thumbs/p025.jpg",
    "pages/thumbs/p026.jpg",
    "pages/thumbs/p027.jpg",
    "pages/thumbs/p028.jpg",
    "pages/thumbs/p029.jpg",
    "pages/thumbs/p030.jpg",
    "pages/thumbs/p031.jpg",
    "pages/thumbs/p032.jpg",
    "pages/thumbs/p033.jpg",
    "pages/thumbs/p034.jpg",
    "pages/thumbs/p035.jpg",
    "pages/thumbs/p036.jpg",
    "pages/thumbs/p037.jpg",
    "pages/thumbs/p038.jpg",
    "pages/thumbs/p039.jpg",
    "pages/thumbs/p040.jpg",
    "pages/thumbs/p041.jpg",
    "pages/thumbs/p042.jpg",
    "pages/thumbs/p043.jpg",
    "pages/thumbs/p044.jpg",
    "pages/thumbs/p045.jpg",
    "pages/thumbs/p046.jpg",
    "pages/thumbs/p047.jpg",
    "pages/thumbs/p048.jpg",
    "pages/thumbs/p049.jpg",
    "pages/thumbs/p050.jpg",
    "pages/thumbs/p051.jpg",
    "pages/thumbs/p052.jpg",
    "pages/thumbs/p053.jpg",
    "pages/thumbs/p054.jpg",
    "pages/thumbs/p055.jpg",
    "pages/thumbs/p056.jpg",
    "pages/thumbs/p057.jpg",
    "pages/thumbs/p058.jpg",
    "pages/thumbs/p059.jpg",
    "pages/thumbs/p060.jpg",
    "pages/thumbs/p061.jpg",
    "pages/thumbs/p062.jpg",
    "pages/thumbs/p063.jpg",
    "pages/thumbs/p064.jpg",
    "pages/thumbs/p065.jpg",
    "pages/thumbs/p066.jpg",
    "pages/thumbs/p067.jpg",
    "pages/thumbs/p068.jpg",
    "pages/thumbs/p069.jpg",
    "pages/thumbs/p070.jpg",
    "pages/thumbs/p071.jpg",
    "pages/thumbs/p072.jpg",
    "pages/thumbs/p073.jpg",
    "pages/thumbs/p074.jpg"
  ]
};
